env:
    global:
        - MOZ_HEADLESS=1
dist: bionic
os:
    - linux
    - osx
language: node_js
node_js:
    - 13
install:
    - npm install -g codecov
addons:
    chrome: stable
    firefox: latest
script:
    - node_modules/karma/bin/karma start karma.conf.js --single-run
    - codecov
services:
    - xvfb
before_install:
    - export DISPLAY=:99.0
before_script:
    - npm install
