language: node_js
node_js:
    - 13
addons:
    chrome: stable
script: node_modules/karma/bin/karma start karma.conf.js --single-run
services:
    - xvfb
before_install:
    - export DISPLAY=:99.0
before_script:
    - npm install
