# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          install-npm: true
          node-version: '19.2.0'
      - run:
          name: Install packages
          command: npm install
      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2
  build:
    jobs:
      - build
